# Generated by Django 4.1 on 2025-10-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
