# Generated by Django 4.1 on 2025-10-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_companyprofile_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='resume_link',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
