# Generated by Django 4.1 on 2025-11-26 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_studentprofile_resume_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='resume_link',
            new_name='resume',
        ),
    ]
