# Generated by Django 4.1 on 2025-11-27 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_resume_link_studentprofile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
