# Generated by Django 4.1 on 2025-11-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_resource_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file_link',
            field=models.FileField(upload_to='resources/'),
        ),
    ]
